# Generated by Django 5.0.2 on 2025-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_website', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
