# Generated by Django 5.0.2 on 2025-12-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIdDetails',
            fields=[
                ('order_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cust_email', models.CharField(max_length=50)),
                ('mobile_number', models.BigIntegerField(default=0)),
                ('cust_name', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_website_plan', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('payment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_manager.orderiddetails')),
                ('plan_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_manager.plandetails')),
            ],
        ),
        migrations.AddField(
            model_name='orderiddetails',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_manager.plandetails'),
        ),
    ]
