# Generated by Django 5.0.2 on 2025-12-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIdDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('cust_email', models.CharField(max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_manager.plandetails')),
            ],
        ),
    ]
