# Generated by Django 5.0.2 on 2025-12-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_manager', '0002_orderiddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderiddetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderiddetails',
            name='order_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('payment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_manager.orderiddetails')),
                ('plan_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_manager.plandetails')),
            ],
        ),
    ]
