# Generated by Django 5.0.2 on 2025-12-14 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_manager', '0003_remove_orderiddetails_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
